// Code generated by PDFlexgo; DO NOT EDIT.
package pdflexgo

import (
	"github.com/kjk/flex"
)

{{ range . -}}
func (block *Block) {{ .Name }}({{ .Param }} {{ .Type }}) *Block {
	block.getFlexNode().StyleSet{{ .Name }}({{ .TypeInternal }}({{ .Param }}))
	return block
}

{{ end }}