// Code generated by PDFlexgo; DO NOT EDIT.
package pdflexgo

import "github.com/kjk/flex"

// CHILDREN

func (block *BlockElement) Children(children ...Node) *BlockElement {

	for _, child := range children {
		block.getFlexNode().InsertChild(child.getFlexNode(), len(block.getFlexNode().Children))
		block.children = append(block.children, child)
	}

	return block
}

// DIRECTION

func (block *BlockElement) Direction(direction Direction) *BlockElement {
	block.getFlexNode().StyleSetDirection(flex.Direction(direction))
	return block
}

func (block *BlockElement) DirectionInherit() *BlockElement {
	return block.Direction(DirectionInherit)
}

func (block *BlockElement) DirectionLTR() *BlockElement {
	return block.Direction(DirectionLTR)
}

func (block *BlockElement) DirectionRTL() *BlockElement {
	return block.Direction(DirectionRTL)
}

// FLEX DIRECTION

func (block *BlockElement) FlexDirection(direction FlexDirection) *BlockElement {
	block.getFlexNode().StyleSetFlexDirection(flex.FlexDirection(direction))
	return block
}

func (block *BlockElement) FlexDirectionColumn() *BlockElement {
	return block.FlexDirection(FlexDirectionColumn)
}

func (block *BlockElement) FlexDirectionColumnReverse() *BlockElement {
	return block.FlexDirection(FlexDirectionColumnReverse)
}

func (block *BlockElement) FlexDirectionRow() *BlockElement {
	return block.FlexDirection(FlexDirectionRow)
}

func (block *BlockElement) FlexDirectionRowReverse() *BlockElement {
	return block.FlexDirection(FlexDirectionRowReverse)
}

// JustifyContent
func (block *BlockElement) Justify(justification Justify) *BlockElement {
	block.getFlexNode().StyleSetJustifyContent(flex.Justify(justification))
	return block
}

func (block *BlockElement) JustifyStart() *BlockElement {
	return block.Justify(JustifyStart)
}

func (block *BlockElement) JustifyCenter() *BlockElement {
	return block.Justify(JustifyCenter)
}

func (block *BlockElement) JustifyEnd() *BlockElement {
	return block.Justify(JustifyEnd)
}

func (block *BlockElement) JustifySpaceBetween() *BlockElement {
	return block.Justify(JustifySpaceBetween)
}

func (block *BlockElement) JustifySpaceAround() *BlockElement {
	return block.Justify(JustifySpaceAround)
}

// ALIGN CONTENT

func (block *BlockElement) AlignContentType(align Align) *BlockElement {
	block.getFlexNode().StyleSetAlignContent(flex.Align(align))
	return block
}

func (block *BlockElement) AlignContentAuto() *BlockElement {
	block.AlignContentType(AlignAuto)
	return block
}

func (block *BlockElement) AlignContentStart() *BlockElement {
	block.AlignContentType(AlignStart)
	return block
}

func (block *BlockElement) AlignContentCenter() *BlockElement {
	block.AlignContentType(AlignCenter)
	return block
}

func (block *BlockElement) AlignContentEnd() *BlockElement {
	block.AlignContentType(AlignEnd)
	return block
}

func (block *BlockElement) AlignContentStretch() *BlockElement {
	block.AlignContentType(AlignStretch)
	return block
}

func (block *BlockElement) AlignContentBaseline() *BlockElement {
	block.AlignContentType(AlignBaseline)
	return block
}

func (block *BlockElement) AlignContentSpaceBetween() *BlockElement {
	block.AlignContentType(AlignSpaceBetween)
	return block
}

func (block *BlockElement) AlignContentSpaceAround() *BlockElement {
	block.AlignContentType(AlignSpaceAround)
	return block
}

// ALIGN ITEMS

func (block *BlockElement) AlignItemsType(align Align) *BlockElement {
	block.getFlexNode().StyleSetAlignItems(flex.Align(align))
	return block
}

func (block *BlockElement) AlignItemsAuto() *BlockElement {
	block.AlignItemsType(AlignAuto)
	return block
}

func (block *BlockElement) AlignItemsStart() *BlockElement {
	block.AlignItemsType(AlignStart)
	return block
}

func (block *BlockElement) AlignItemsCenter() *BlockElement {
	block.AlignItemsType(AlignCenter)
	return block
}

func (block *BlockElement) AlignItemsEnd() *BlockElement {
	block.AlignItemsType(AlignEnd)
	return block
}

func (block *BlockElement) AlignItemsStretch() *BlockElement {
	block.AlignItemsType(AlignStretch)
	return block
}

func (block *BlockElement) AlignItemsBaseline() *BlockElement {
	block.AlignItemsType(AlignBaseline)
	return block
}

func (block *BlockElement) AlignItemsSpaceBetween() *BlockElement {
	block.AlignItemsType(AlignSpaceBetween)
	return block
}

func (block *BlockElement) AlignItemsSpaceAround() *BlockElement {
	block.AlignItemsType(AlignSpaceAround)
	return block
}

// FLEX WRAP

func (block *BlockElement) FlexWrapValue(wrapValue Wrap) *BlockElement {
	block.getFlexNode().StyleSetFlexWrap(flex.Wrap(wrapValue))
	return block
}

func (block *BlockElement) FlexNoWrap() *BlockElement {
	return block.FlexWrapValue(WrapNoWrap)
}

func (block *BlockElement) FlexWrap() *BlockElement {
	return block.FlexWrapValue(WrapWrap)
}

func (block *BlockElement) FlexWrapReverse() *BlockElement {
	return block.FlexWrapValue(WrapWrapReverse)
}
