// Code generated by PDFlexgo; DO NOT EDIT.
package pdflexgo

import (
	"github.com/kjk/flex"
)

func (block *Block) MarginTop(margin float64) *Block {
	block.getFlexNode().StyleSetMargin(flex.EdgeTop, float32(margin))

	return block
}

func (block *Block) MarginRight(margin float64) *Block {
	block.getFlexNode().StyleSetMargin(flex.EdgeRight, float32(margin))

	return block
}

func (block *Block) MarginBottom(margin float64) *Block {
	block.getFlexNode().StyleSetMargin(flex.EdgeBottom, float32(margin))

	return block
}

func (block *Block) MarginLeft(margin float64) *Block {
	block.getFlexNode().StyleSetMargin(flex.EdgeLeft, float32(margin))

	return block
}


func (block *Block) GetMarginTop() float64 {
	return float64(block.getFlexNode().StyleGetMargin(flex.EdgeTop).Value)
}

func (block *Block) GetMarginRight() float64 {
	return float64(block.getFlexNode().StyleGetMargin(flex.EdgeRight).Value)
}

func (block *Block) GetMarginBottom() float64 {
	return float64(block.getFlexNode().StyleGetMargin(flex.EdgeBottom).Value)
}

func (block *Block) GetMarginLeft() float64 {
	return float64(block.getFlexNode().StyleGetMargin(flex.EdgeLeft).Value)
}



func (block *Block) Margin(top float64, right float64, bottom float64, left float64) *Block {
	block.
		MarginTop(top).
		MarginRight(right).
		MarginBottom(bottom).
		MarginLeft(left)

	return block
}

func (block *Block) MarginVertical(margin float64) *Block {
	block.
		MarginTop(margin).
		MarginBottom(margin)

	return block
}

func (block *Block) MarginHorizontal(margin float64) *Block {
	block.
		MarginLeft(margin).
		MarginRight(margin)

	return block
}

func (block *Block) MarginAll(margin float64) *Block {
	block.
		MarginTop(margin).
		MarginRight(margin).
		MarginBottom(margin).
		MarginLeft(margin)

	return block
}

func (block *Block) PaddingTop(padding float64) *Block {
	block.getFlexNode().StyleSetPadding(flex.EdgeTop, float32(padding))

	return block
}

func (block *Block) PaddingRight(padding float64) *Block {
	block.getFlexNode().StyleSetPadding(flex.EdgeRight, float32(padding))

	return block
}

func (block *Block) PaddingBottom(padding float64) *Block {
	block.getFlexNode().StyleSetPadding(flex.EdgeBottom, float32(padding))

	return block
}

func (block *Block) PaddingLeft(padding float64) *Block {
	block.getFlexNode().StyleSetPadding(flex.EdgeLeft, float32(padding))

	return block
}


func (block *Block) GetPaddingTop() float64 {
	return float64(block.getFlexNode().StyleGetPadding(flex.EdgeTop).Value)
}

func (block *Block) GetPaddingRight() float64 {
	return float64(block.getFlexNode().StyleGetPadding(flex.EdgeRight).Value)
}

func (block *Block) GetPaddingBottom() float64 {
	return float64(block.getFlexNode().StyleGetPadding(flex.EdgeBottom).Value)
}

func (block *Block) GetPaddingLeft() float64 {
	return float64(block.getFlexNode().StyleGetPadding(flex.EdgeLeft).Value)
}



func (block *Block) Padding(top float64, right float64, bottom float64, left float64) *Block {
	block.
		PaddingTop(top).
		PaddingRight(right).
		PaddingBottom(bottom).
		PaddingLeft(left)

	return block
}

func (block *Block) PaddingVertical(padding float64) *Block {
	block.
		PaddingTop(padding).
		PaddingBottom(padding)

	return block
}

func (block *Block) PaddingHorizontal(padding float64) *Block {
	block.
		PaddingLeft(padding).
		PaddingRight(padding)

	return block
}

func (block *Block) PaddingAll(padding float64) *Block {
	block.
		PaddingTop(padding).
		PaddingRight(padding).
		PaddingBottom(padding).
		PaddingLeft(padding)

	return block
}

