// Code generated by PDFlexgo; DO NOT EDIT.
package pdflexgo

import (
	"github.com/kjk/flex"
)

func (block *BlockElement) MarginTop(margin float64) *BlockElement {
	block.getFlexNode().StyleSetMargin(flex.EdgeTop, float32(margin))

	return block
}

func (block *BlockElement) MarginRight(margin float64) *BlockElement {
	block.getFlexNode().StyleSetMargin(flex.EdgeRight, float32(margin))

	return block
}

func (block *BlockElement) MarginBottom(margin float64) *BlockElement {
	block.getFlexNode().StyleSetMargin(flex.EdgeBottom, float32(margin))

	return block
}

func (block *BlockElement) MarginLeft(margin float64) *BlockElement {
	block.getFlexNode().StyleSetMargin(flex.EdgeLeft, float32(margin))

	return block
}


func (block *BlockElement) GetMarginTop() float64 {
	return float64(block.getFlexNode().StyleGetMargin(flex.EdgeTop).Value)
}

func (block *BlockElement) GetMarginRight() float64 {
	return float64(block.getFlexNode().StyleGetMargin(flex.EdgeRight).Value)
}

func (block *BlockElement) GetMarginBottom() float64 {
	return float64(block.getFlexNode().StyleGetMargin(flex.EdgeBottom).Value)
}

func (block *BlockElement) GetMarginLeft() float64 {
	return float64(block.getFlexNode().StyleGetMargin(flex.EdgeLeft).Value)
}



func (block *BlockElement) Margin(top float64, right float64, bottom float64, left float64) *BlockElement {
	block.
		MarginTop(top).
		MarginRight(right).
		MarginBottom(bottom).
		MarginLeft(left)

	return block
}

func (block *BlockElement) MarginVertical(margin float64) *BlockElement {
	block.
		MarginTop(margin).
		MarginBottom(margin)

	return block
}

func (block *BlockElement) MarginHorizontal(margin float64) *BlockElement {
	block.
		MarginLeft(margin).
		MarginRight(margin)

	return block
}

func (block *BlockElement) MarginAll(margin float64) *BlockElement {
	block.
		MarginTop(margin).
		MarginRight(margin).
		MarginBottom(margin).
		MarginLeft(margin)

	return block
}

func (block *BlockElement) MarginPercentTop(percent float64) *BlockElement {
	block.getFlexNode().StyleSetMarginPercent(flex.EdgeTop, float32(percent))

	return block
}

func (block *BlockElement) MarginPercentRight(percent float64) *BlockElement {
	block.getFlexNode().StyleSetMarginPercent(flex.EdgeRight, float32(percent))

	return block
}

func (block *BlockElement) MarginPercentBottom(percent float64) *BlockElement {
	block.getFlexNode().StyleSetMarginPercent(flex.EdgeBottom, float32(percent))

	return block
}

func (block *BlockElement) MarginPercentLeft(percent float64) *BlockElement {
	block.getFlexNode().StyleSetMarginPercent(flex.EdgeLeft, float32(percent))

	return block
}


func (block *BlockElement) MarginPercent(top float64, right float64, bottom float64, left float64) *BlockElement {
	block.
		MarginPercentTop(top).
		MarginPercentRight(right).
		MarginPercentBottom(bottom).
		MarginPercentLeft(left)

	return block
}

func (block *BlockElement) MarginPercentVertical(percent float64) *BlockElement {
	block.
		MarginPercentTop(percent).
		MarginPercentBottom(percent)

	return block
}

func (block *BlockElement) MarginPercentHorizontal(percent float64) *BlockElement {
	block.
		MarginPercentLeft(percent).
		MarginPercentRight(percent)

	return block
}

func (block *BlockElement) MarginPercentAll(percent float64) *BlockElement {
	block.
		MarginPercentTop(percent).
		MarginPercentRight(percent).
		MarginPercentBottom(percent).
		MarginPercentLeft(percent)

	return block
}

func (block *BlockElement) PaddingTop(padding float64) *BlockElement {
	block.getFlexNode().StyleSetPadding(flex.EdgeTop, float32(padding))

	return block
}

func (block *BlockElement) PaddingRight(padding float64) *BlockElement {
	block.getFlexNode().StyleSetPadding(flex.EdgeRight, float32(padding))

	return block
}

func (block *BlockElement) PaddingBottom(padding float64) *BlockElement {
	block.getFlexNode().StyleSetPadding(flex.EdgeBottom, float32(padding))

	return block
}

func (block *BlockElement) PaddingLeft(padding float64) *BlockElement {
	block.getFlexNode().StyleSetPadding(flex.EdgeLeft, float32(padding))

	return block
}


func (block *BlockElement) GetPaddingTop() float64 {
	return float64(block.getFlexNode().StyleGetPadding(flex.EdgeTop).Value)
}

func (block *BlockElement) GetPaddingRight() float64 {
	return float64(block.getFlexNode().StyleGetPadding(flex.EdgeRight).Value)
}

func (block *BlockElement) GetPaddingBottom() float64 {
	return float64(block.getFlexNode().StyleGetPadding(flex.EdgeBottom).Value)
}

func (block *BlockElement) GetPaddingLeft() float64 {
	return float64(block.getFlexNode().StyleGetPadding(flex.EdgeLeft).Value)
}



func (block *BlockElement) Padding(top float64, right float64, bottom float64, left float64) *BlockElement {
	block.
		PaddingTop(top).
		PaddingRight(right).
		PaddingBottom(bottom).
		PaddingLeft(left)

	return block
}

func (block *BlockElement) PaddingVertical(padding float64) *BlockElement {
	block.
		PaddingTop(padding).
		PaddingBottom(padding)

	return block
}

func (block *BlockElement) PaddingHorizontal(padding float64) *BlockElement {
	block.
		PaddingLeft(padding).
		PaddingRight(padding)

	return block
}

func (block *BlockElement) PaddingAll(padding float64) *BlockElement {
	block.
		PaddingTop(padding).
		PaddingRight(padding).
		PaddingBottom(padding).
		PaddingLeft(padding)

	return block
}

func (block *BlockElement) PaddingPercentTop(percent float64) *BlockElement {
	block.getFlexNode().StyleSetPaddingPercent(flex.EdgeTop, float32(percent))

	return block
}

func (block *BlockElement) PaddingPercentRight(percent float64) *BlockElement {
	block.getFlexNode().StyleSetPaddingPercent(flex.EdgeRight, float32(percent))

	return block
}

func (block *BlockElement) PaddingPercentBottom(percent float64) *BlockElement {
	block.getFlexNode().StyleSetPaddingPercent(flex.EdgeBottom, float32(percent))

	return block
}

func (block *BlockElement) PaddingPercentLeft(percent float64) *BlockElement {
	block.getFlexNode().StyleSetPaddingPercent(flex.EdgeLeft, float32(percent))

	return block
}


func (block *BlockElement) PaddingPercent(top float64, right float64, bottom float64, left float64) *BlockElement {
	block.
		PaddingPercentTop(top).
		PaddingPercentRight(right).
		PaddingPercentBottom(bottom).
		PaddingPercentLeft(left)

	return block
}

func (block *BlockElement) PaddingPercentVertical(percent float64) *BlockElement {
	block.
		PaddingPercentTop(percent).
		PaddingPercentBottom(percent)

	return block
}

func (block *BlockElement) PaddingPercentHorizontal(percent float64) *BlockElement {
	block.
		PaddingPercentLeft(percent).
		PaddingPercentRight(percent)

	return block
}

func (block *BlockElement) PaddingPercentAll(percent float64) *BlockElement {
	block.
		PaddingPercentTop(percent).
		PaddingPercentRight(percent).
		PaddingPercentBottom(percent).
		PaddingPercentLeft(percent)

	return block
}

func (block *BlockElement) BorderTop(border float64) *BlockElement {
	block.getFlexNode().StyleSetBorder(flex.EdgeTop, float32(border))

	return block
}

func (block *BlockElement) BorderRight(border float64) *BlockElement {
	block.getFlexNode().StyleSetBorder(flex.EdgeRight, float32(border))

	return block
}

func (block *BlockElement) BorderBottom(border float64) *BlockElement {
	block.getFlexNode().StyleSetBorder(flex.EdgeBottom, float32(border))

	return block
}

func (block *BlockElement) BorderLeft(border float64) *BlockElement {
	block.getFlexNode().StyleSetBorder(flex.EdgeLeft, float32(border))

	return block
}


func (block *BlockElement) Border(top float64, right float64, bottom float64, left float64) *BlockElement {
	block.
		BorderTop(top).
		BorderRight(right).
		BorderBottom(bottom).
		BorderLeft(left)

	return block
}

func (block *BlockElement) BorderVertical(border float64) *BlockElement {
	block.
		BorderTop(border).
		BorderBottom(border)

	return block
}

func (block *BlockElement) BorderHorizontal(border float64) *BlockElement {
	block.
		BorderLeft(border).
		BorderRight(border)

	return block
}

func (block *BlockElement) BorderAll(border float64) *BlockElement {
	block.
		BorderTop(border).
		BorderRight(border).
		BorderBottom(border).
		BorderLeft(border)

	return block
}

func (block *BlockElement) PositionTop(position float64) *BlockElement {
	block.getFlexNode().StyleSetPosition(flex.EdgeTop, float32(position))

	return block
}

func (block *BlockElement) PositionRight(position float64) *BlockElement {
	block.getFlexNode().StyleSetPosition(flex.EdgeRight, float32(position))

	return block
}

func (block *BlockElement) PositionBottom(position float64) *BlockElement {
	block.getFlexNode().StyleSetPosition(flex.EdgeBottom, float32(position))

	return block
}

func (block *BlockElement) PositionLeft(position float64) *BlockElement {
	block.getFlexNode().StyleSetPosition(flex.EdgeLeft, float32(position))

	return block
}


func (block *BlockElement) GetPositionTop() float64 {
	return float64(block.getFlexNode().StyleGetPosition(flex.EdgeTop).Value)
}

func (block *BlockElement) GetPositionRight() float64 {
	return float64(block.getFlexNode().StyleGetPosition(flex.EdgeRight).Value)
}

func (block *BlockElement) GetPositionBottom() float64 {
	return float64(block.getFlexNode().StyleGetPosition(flex.EdgeBottom).Value)
}

func (block *BlockElement) GetPositionLeft() float64 {
	return float64(block.getFlexNode().StyleGetPosition(flex.EdgeLeft).Value)
}



func (block *BlockElement) Position(top float64, right float64, bottom float64, left float64) *BlockElement {
	block.
		PositionTop(top).
		PositionRight(right).
		PositionBottom(bottom).
		PositionLeft(left)

	return block
}

func (block *BlockElement) PositionVertical(position float64) *BlockElement {
	block.
		PositionTop(position).
		PositionBottom(position)

	return block
}

func (block *BlockElement) PositionHorizontal(position float64) *BlockElement {
	block.
		PositionLeft(position).
		PositionRight(position)

	return block
}

func (block *BlockElement) PositionAll(position float64) *BlockElement {
	block.
		PositionTop(position).
		PositionRight(position).
		PositionBottom(position).
		PositionLeft(position)

	return block
}

func (block *BlockElement) PositionPercentTop(percent float64) *BlockElement {
	block.getFlexNode().StyleSetPositionPercent(flex.EdgeTop, float32(percent))

	return block
}

func (block *BlockElement) PositionPercentRight(percent float64) *BlockElement {
	block.getFlexNode().StyleSetPositionPercent(flex.EdgeRight, float32(percent))

	return block
}

func (block *BlockElement) PositionPercentBottom(percent float64) *BlockElement {
	block.getFlexNode().StyleSetPositionPercent(flex.EdgeBottom, float32(percent))

	return block
}

func (block *BlockElement) PositionPercentLeft(percent float64) *BlockElement {
	block.getFlexNode().StyleSetPositionPercent(flex.EdgeLeft, float32(percent))

	return block
}


func (block *BlockElement) PositionPercent(top float64, right float64, bottom float64, left float64) *BlockElement {
	block.
		PositionPercentTop(top).
		PositionPercentRight(right).
		PositionPercentBottom(bottom).
		PositionPercentLeft(left)

	return block
}

func (block *BlockElement) PositionPercentVertical(percent float64) *BlockElement {
	block.
		PositionPercentTop(percent).
		PositionPercentBottom(percent)

	return block
}

func (block *BlockElement) PositionPercentHorizontal(percent float64) *BlockElement {
	block.
		PositionPercentLeft(percent).
		PositionPercentRight(percent)

	return block
}

func (block *BlockElement) PositionPercentAll(percent float64) *BlockElement {
	block.
		PositionPercentTop(percent).
		PositionPercentRight(percent).
		PositionPercentBottom(percent).
		PositionPercentLeft(percent)

	return block
}

