// Code generated by PDFlexgo; DO NOT EDIT.
package pdflexgo

import (
	"github.com/kjk/flex"
)

func (block *Block) FlexGrow(grow float64) *Block {
	block.getFlexNode().StyleSetFlexGrow(float32(grow))
	return block
}

func (block *Block) FlexShrink(shrink float64) *Block {
	block.getFlexNode().StyleSetFlexShrink(float32(shrink))
	return block
}

func (block *Block) FlexDirection(direction FlexDirection) *Block {
	block.getFlexNode().StyleSetFlexDirection(flex.FlexDirection(direction))
	return block
}

