// Code generated by PDFlexgo; DO NOT EDIT.
package pdflexgo

import (
	"github.com/kjk/flex"
)

// MARGIN

func (body *Body) MarginTop(margin float64) *Body {
	body.delegated.getFlexNode().StyleSetMargin(flex.EdgeTop, float32(margin))
	return body
}
func (body *Body) MarginRight(margin float64) *Body {
	body.delegated.getFlexNode().StyleSetMargin(flex.EdgeRight, float32(margin))
	return body
}
func (body *Body) MarginBottom(margin float64) *Body {
	body.delegated.getFlexNode().StyleSetMargin(flex.EdgeBottom, float32(margin))
	return body
}
func (body *Body) MarginLeft(margin float64) *Body {
	body.delegated.getFlexNode().StyleSetMargin(flex.EdgeLeft, float32(margin))
	return body
}
func (body *Body) MarginHorizontal(margin float64) *Body {
	body.MarginLeft(margin).MarginRight(margin)
	return body
}
func (body *Body) MarginVertical(margin float64) *Body {
	body.delegated.MarginTop(margin).MarginBottom(margin)
	return body
}
func (body *Body) MarginAll(margin float64) *Body {
	body.delegated.MarginHorizontal(margin).MarginVertical(margin)
	return body
}
func (body *Body) Margin(top float64, right float64, bottom float64, left float64) *Body {
	body.delegated.
		MarginTop(top).
		MarginRight(right).
		MarginBottom(bottom).
		MarginLeft(left)
	return body
}

// MARGIN PERCENT

func (body *Body) MarginPercentTop(margin float64) *Body {
	body.delegated.getFlexNode().StyleSetMarginPercent(flex.EdgeTop, float32(margin))
	return body
}

func (body *Body) MarginPercentRight(margin float64) *Body {
	body.delegated.getFlexNode().StyleSetMarginPercent(flex.EdgeRight, float32(margin))
	return body
}

func (body *Body) MarginPercentBottom(margin float64) *Body {
	body.delegated.getFlexNode().StyleSetMarginPercent(flex.EdgeBottom, float32(margin))
	return body
}

func (body *Body) MarginPercentLeft(margin float64) *Body {
	body.delegated.getFlexNode().StyleSetMarginPercent(flex.EdgeLeft, float32(margin))
	return body
}

func (body *Body) MarginPercentHorizontal(margin float64) *Body {
	body.delegated.MarginPercentLeft(margin).MarginPercentRight(margin)
	return body
}

func (body *Body) MarginPercentVertical(margin float64) *Body {
	body.delegated.MarginPercentTop(margin).MarginPercentBottom(margin)
	return body
}

func (body *Body) MarginPercentAll(margin float64) *Body {
	body.delegated.MarginPercentHorizontal(margin).MarginPercentVertical(margin)
	return body
}

// PADDING

// For Padding

func (body *Body) PaddingTop(padding float64) *Body {
	body.delegated.getFlexNode().StyleSetPadding(flex.EdgeTop, float32(padding))
	return body
}

func (body *Body) PaddingRight(padding float64) *Body {
	body.delegated.getFlexNode().StyleSetPadding(flex.EdgeRight, float32(padding))
	return body
}

func (body *Body) PaddingBottom(padding float64) *Body {
	body.delegated.getFlexNode().StyleSetPadding(flex.EdgeBottom, float32(padding))
	return body
}

func (body *Body) PaddingLeft(padding float64) *Body {
	body.delegated.getFlexNode().StyleSetPadding(flex.EdgeLeft, float32(padding))
	return body
}

func (body *Body) PaddingHorizontal(padding float64) *Body {
	body.delegated.PaddingLeft(padding).PaddingRight(padding)
	return body
}

func (body *Body) PaddingVertical(padding float64) *Body {
	body.delegated.PaddingTop(padding).PaddingBottom(padding)
	return body
}

func (body *Body) PaddingAll(padding float64) *Body {
	body.delegated.PaddingHorizontal(padding).PaddingVertical(padding)
	return body
}

func (body *Body) Padding(top float64, right float64, bottom float64, left float64) *Body {
	body.delegated.
		PaddingTop(top).
		PaddingRight(right).
		PaddingBottom(bottom).
		PaddingLeft(left)
	return body
}

// PADDING PERCENT

func (body *Body) PaddingPercentTop(padding float64) *Body {
	body.delegated.getFlexNode().StyleSetPaddingPercent(flex.EdgeTop, float32(padding))
	return body
}

func (body *Body) PaddingPercentRight(padding float64) *Body {
	body.delegated.getFlexNode().StyleSetPaddingPercent(flex.EdgeRight, float32(padding))
	return body
}

func (body *Body) PaddingPercentBottom(padding float64) *Body {
	body.delegated.getFlexNode().StyleSetPaddingPercent(flex.EdgeBottom, float32(padding))
	return body
}

func (body *Body) PaddingPercentLeft(padding float64) *Body {
	body.delegated.getFlexNode().StyleSetPaddingPercent(flex.EdgeLeft, float32(padding))
	return body
}

func (body *Body) PaddingPercentHorizontal(padding float64) *Body {
	body.delegated.PaddingPercentLeft(padding).PaddingPercentRight(padding)
	return body
}

func (body *Body) PaddingPercentVertical(padding float64) *Body {
	body.delegated.PaddingPercentTop(padding).PaddingPercentBottom(padding)
	return body
}

func (body *Body) PaddingPercentAll(padding float64) *Body {
	body.delegated.PaddingPercentHorizontal(padding).PaddingPercentVertical(padding)
	return body
}

func (body *Body) PaddingPercent(top float64, right float64, bottom float64, left float64) *Body {
	body.delegated.
		PaddingPercentTop(top).
		PaddingPercentRight(right).
		PaddingPercentBottom(bottom).
		PaddingPercentLeft(left)
	return body
}

// BORDERWIDTH

func (body *Body) BorderWidthTop(borderWidth float64) *Body {
	body.delegated.getFlexNode().StyleSetBorder(flex.EdgeTop, float32(borderWidth))
	return body
}

func (body *Body) BorderWidthRight(borderWidth float64) *Body {
	body.delegated.getFlexNode().StyleSetBorder(flex.EdgeRight, float32(borderWidth))
	return body
}

func (body *Body) BorderWidthBottom(borderWidth float64) *Body {
	body.delegated.getFlexNode().StyleSetBorder(flex.EdgeBottom, float32(borderWidth))
	return body
}

func (body *Body) BorderWidthLeft(borderWidth float64) *Body {
	body.delegated.getFlexNode().StyleSetBorder(flex.EdgeLeft, float32(borderWidth))
	return body
}

func (body *Body) BorderWidthHorizontal(borderWidth float64) *Body {
	body.delegated.BorderWidthLeft(borderWidth).BorderWidthRight(borderWidth)
	return body
}

func (body *Body) BorderWidthVertical(borderWidth float64) *Body {
	body.delegated.BorderWidthTop(borderWidth).BorderWidthBottom(borderWidth)
	return body
}

func (body *Body) BorderWidthAll(borderWidth float64) *Body {
	body.delegated.BorderWidthHorizontal(borderWidth).BorderWidthVertical(borderWidth)
	return body
}

func (body *Body) BorderWidth(top float64, right float64, bottom float64, left float64) *Body {
	body.delegated.
		BorderWidthTop(top).
		BorderWidthRight(right).
		BorderWidthBottom(bottom).
		BorderWidthLeft(left)
	return body
}

// BACKGROUND

func (body *Body) BackgroundColor(red int, green int, blue int, alpha ...float64) *Body {
	body.delegated.backgroundColor = getRgba(red, green, blue, alpha...)
	return body
}

// BORDER COLOR

func (body *Body) BorderColorTop(red int, green int, blue int, alpha ...float64) *Body {
	body.delegated.borderColor[EdgeTop] = getRgba(red, green, blue, alpha...)
	return body
}

func (body *Body) BorderColorRight(red int, green int, blue int, alpha ...float64) *Body {
	body.delegated.borderColor[EdgeRight] = getRgba(red, green, blue, alpha...)
	return body
}

func (body *Body) BorderColorBottom(red int, green int, blue int, alpha ...float64) *Body {
	body.delegated.borderColor[EdgeBottom] = getRgba(red, green, blue, alpha...)
	return body
}

func (body *Body) BorderColorLeft(red int, green int, blue int, alpha ...float64) *Body {
	body.delegated.borderColor[EdgeLeft] = getRgba(red, green, blue, alpha...)
	return body
}

func (body *Body) BorderColorHorizontal(red int, green int, blue int, alpha ...float64) *Body {
	body.delegated.
		BorderColorLeft(red, green, blue, alpha...).
		BorderColorRight(red, green, blue, alpha...)
	return body
}

func (body *Body) BorderColorVertical(red int, green int, blue int, alpha ...float64) *Body {
	body.delegated.
		BorderColorTop(red, green, blue, alpha...).
		BorderColorBottom(red, green, blue, alpha...)
	return body
}

func (body *Body) BorderColorAll(red int, green int, blue int, alpha ...float64) *Body {
	body.delegated.
		BorderColorHorizontal(red, green, blue, alpha...).
		BorderColorVertical(red, green, blue, alpha...)
	return body
}
