// Code generated by PDFlexgo; DO NOT EDIT.
package pdflexgo

import "github.com/kjk/flex"

// CHILDREN

func (footer *Footer) Children(children ...Node) *Footer {

	for _, child := range children {
		footer.delegated.getFlexNode().InsertChild(child.getFlexNode(), len(footer.delegated.getFlexNode().Children))
		footer.delegated.children = append(footer.delegated.children, child)
	}

	return footer
}

// DIRECTION

func (footer *Footer) Direction(direction Direction) *Footer {
	footer.delegated.getFlexNode().StyleSetDirection(flex.Direction(direction))
	return footer
}

func (footer *Footer) DirectionInherit() *Footer {
	footer.delegated.Direction(DirectionInherit)
	return footer
}

func (footer *Footer) DirectionLTR() *Footer {
	footer.delegated.Direction(DirectionLTR)
	return footer
}

func (footer *Footer) DirectionRTL() *Footer {
	footer.delegated.Direction(DirectionRTL)
	return footer
}

// FLEX DIRECTION

func (footer *Footer) FlexDirection(direction FlexDirection) *Footer {
	footer.delegated.getFlexNode().StyleSetFlexDirection(flex.FlexDirection(direction))
	return footer
}

func (footer *Footer) FlexDirectionColumn() *Footer {
	footer.delegated.FlexDirection(FlexDirectionColumn)
	return footer
}

func (footer *Footer) FlexDirectionColumnReverse() *Footer {
	footer.delegated.FlexDirection(FlexDirectionColumnReverse)
	return footer
}

func (footer *Footer) FlexDirectionRow() *Footer {
	footer.delegated.FlexDirection(FlexDirectionRow)
	return footer
}

func (footer *Footer) FlexDirectionRowReverse() *Footer {
	footer.delegated.FlexDirection(FlexDirectionRowReverse)
	return footer
}

// JustifyContent
func (footer *Footer) JustifyContent(justification Justify) *Footer {
	footer.delegated.getFlexNode().StyleSetJustifyContent(flex.Justify(justification))
	return footer
}

func (footer *Footer) JustifyContentStart() *Footer {
	footer.delegated.JustifyContent(JustifyStart)
	return footer
}

func (footer *Footer) JustifyContentCenter() *Footer {
	footer.delegated.JustifyContent(JustifyCenter)
	return footer
}

func (footer *Footer) JustifyContentEnd() *Footer {
	footer.delegated.JustifyContent(JustifyEnd)
	return footer
}

func (footer *Footer) JustifyContentSpaceBetween() *Footer {
	footer.delegated.JustifyContent(JustifySpaceBetween)
	return footer
}

func (footer *Footer) JustifyContentSpaceAround() *Footer {
	footer.delegated.JustifyContent(JustifySpaceAround)
	return footer
}

// ALIGN CONTENT

func (footer *Footer) AlignContentType(align Align) *Footer {
	footer.delegated.getFlexNode().StyleSetAlignContent(flex.Align(align))
	return footer
}

func (footer *Footer) AlignContentAuto() *Footer {
	footer.delegated.AlignContentType(AlignAuto)
	return footer
}

func (footer *Footer) AlignContentStart() *Footer {
	footer.delegated.AlignContentType(AlignStart)
	return footer
}

func (footer *Footer) AlignContentCenter() *Footer {
	footer.delegated.AlignContentType(AlignCenter)
	return footer
}

func (footer *Footer) AlignContentEnd() *Footer {
	footer.delegated.AlignContentType(AlignEnd)
	return footer
}

func (footer *Footer) AlignContentStretch() *Footer {
	footer.delegated.AlignContentType(AlignStretch)
	return footer
}

func (footer *Footer) AlignContentBaseline() *Footer {
	footer.delegated.AlignContentType(AlignBaseline)
	return footer
}

func (footer *Footer) AlignContentSpaceBetween() *Footer {
	footer.delegated.AlignContentType(AlignSpaceBetween)
	return footer
}

func (footer *Footer) AlignContentSpaceAround() *Footer {
	footer.delegated.AlignContentType(AlignSpaceAround)
	return footer
}

// ALIGN ITEMS

func (footer *Footer) AlignItemsType(align Align) *Footer {
	footer.delegated.getFlexNode().StyleSetAlignItems(flex.Align(align))
	return footer
}

func (footer *Footer) AlignItemsAuto() *Footer {
	footer.delegated.AlignItemsType(AlignAuto)
	return footer
}

func (footer *Footer) AlignItemsStart() *Footer {
	footer.delegated.AlignItemsType(AlignStart)
	return footer
}

func (footer *Footer) AlignItemsCenter() *Footer {
	footer.delegated.AlignItemsType(AlignCenter)
	return footer
}

func (footer *Footer) AlignItemsEnd() *Footer {
	footer.delegated.AlignItemsType(AlignEnd)
	return footer
}

func (footer *Footer) AlignItemsStretch() *Footer {
	footer.delegated.AlignItemsType(AlignStretch)
	return footer
}

func (footer *Footer) AlignItemsBaseline() *Footer {
	footer.delegated.AlignItemsType(AlignBaseline)
	return footer
}

func (footer *Footer) AlignItemsSpaceBetween() *Footer {
	footer.delegated.AlignItemsType(AlignSpaceBetween)
	return footer
}

func (footer *Footer) AlignItemsSpaceAround() *Footer {
	footer.delegated.AlignItemsType(AlignSpaceAround)
	return footer
}

// FLEX WRAP

func (footer *Footer) FlexWrapValue(wrapValue Wrap) *Footer {
	footer.delegated.getFlexNode().StyleSetFlexWrap(flex.Wrap(wrapValue))
	return footer
}

func (footer *Footer) FlexNoWrap() *Footer {
	footer.delegated.FlexWrapValue(WrapNoWrap)
	return footer
}

func (footer *Footer) FlexWrap() *Footer {
	footer.delegated.FlexWrapValue(WrapWrap)
	return footer
}

func (footer *Footer) FlexWrapReverse() *Footer {
	footer.delegated.FlexWrapValue(WrapWrapReverse)
	return footer
}
