// Code generated by PDFlexgo; DO NOT EDIT.
package pdflexgo

import (
	"github.com/kjk/flex"
)

// MARGIN

func (header *Header) MarginTop(margin float64) *Header {
	header.delegated.getFlexNode().StyleSetMargin(flex.EdgeTop, float32(margin))
	return header
}
func (header *Header) MarginRight(margin float64) *Header {
	header.delegated.getFlexNode().StyleSetMargin(flex.EdgeRight, float32(margin))
	return header
}
func (header *Header) MarginBottom(margin float64) *Header {
	header.delegated.getFlexNode().StyleSetMargin(flex.EdgeBottom, float32(margin))
	return header
}
func (header *Header) MarginLeft(margin float64) *Header {
	header.delegated.getFlexNode().StyleSetMargin(flex.EdgeLeft, float32(margin))
	return header
}
func (header *Header) MarginHorizontal(margin float64) *Header {
	header.MarginLeft(margin).MarginRight(margin)
	return header
}
func (header *Header) MarginVertical(margin float64) *Header {
	header.delegated.MarginTop(margin).MarginBottom(margin)
	return header
}
func (header *Header) MarginAll(margin float64) *Header {
	header.delegated.MarginHorizontal(margin).MarginVertical(margin)
	return header
}
func (header *Header) Margin(top float64, right float64, bottom float64, left float64) *Header {
	header.delegated.
		MarginTop(top).
		MarginRight(right).
		MarginBottom(bottom).
		MarginLeft(left)
	return header
}

// MARGIN PERCENT

func (header *Header) MarginPercentTop(margin float64) *Header {
	header.delegated.getFlexNode().StyleSetMarginPercent(flex.EdgeTop, float32(margin))
	return header
}

func (header *Header) MarginPercentRight(margin float64) *Header {
	header.delegated.getFlexNode().StyleSetMarginPercent(flex.EdgeRight, float32(margin))
	return header
}

func (header *Header) MarginPercentBottom(margin float64) *Header {
	header.delegated.getFlexNode().StyleSetMarginPercent(flex.EdgeBottom, float32(margin))
	return header
}

func (header *Header) MarginPercentLeft(margin float64) *Header {
	header.delegated.getFlexNode().StyleSetMarginPercent(flex.EdgeLeft, float32(margin))
	return header
}

func (header *Header) MarginPercentHorizontal(margin float64) *Header {
	header.delegated.MarginPercentLeft(margin).MarginPercentRight(margin)
	return header
}

func (header *Header) MarginPercentVertical(margin float64) *Header {
	header.delegated.MarginPercentTop(margin).MarginPercentBottom(margin)
	return header
}

func (header *Header) MarginPercentAll(margin float64) *Header {
	header.delegated.MarginPercentHorizontal(margin).MarginPercentVertical(margin)
	return header
}

// PADDING

// For Padding

func (header *Header) PaddingTop(padding float64) *Header {
	header.delegated.getFlexNode().StyleSetPadding(flex.EdgeTop, float32(padding))
	return header
}

func (header *Header) PaddingRight(padding float64) *Header {
	header.delegated.getFlexNode().StyleSetPadding(flex.EdgeRight, float32(padding))
	return header
}

func (header *Header) PaddingBottom(padding float64) *Header {
	header.delegated.getFlexNode().StyleSetPadding(flex.EdgeBottom, float32(padding))
	return header
}

func (header *Header) PaddingLeft(padding float64) *Header {
	header.delegated.getFlexNode().StyleSetPadding(flex.EdgeLeft, float32(padding))
	return header
}

func (header *Header) PaddingHorizontal(padding float64) *Header {
	header.delegated.PaddingLeft(padding).PaddingRight(padding)
	return header
}

func (header *Header) PaddingVertical(padding float64) *Header {
	header.delegated.PaddingTop(padding).PaddingBottom(padding)
	return header
}

func (header *Header) PaddingAll(padding float64) *Header {
	header.delegated.PaddingHorizontal(padding).PaddingVertical(padding)
	return header
}

func (header *Header) Padding(top float64, right float64, bottom float64, left float64) *Header {
	header.delegated.
		PaddingTop(top).
		PaddingRight(right).
		PaddingBottom(bottom).
		PaddingLeft(left)
	return header
}

// PADDING PERCENT

func (header *Header) PaddingPercentTop(padding float64) *Header {
	header.delegated.getFlexNode().StyleSetPaddingPercent(flex.EdgeTop, float32(padding))
	return header
}

func (header *Header) PaddingPercentRight(padding float64) *Header {
	header.delegated.getFlexNode().StyleSetPaddingPercent(flex.EdgeRight, float32(padding))
	return header
}

func (header *Header) PaddingPercentBottom(padding float64) *Header {
	header.delegated.getFlexNode().StyleSetPaddingPercent(flex.EdgeBottom, float32(padding))
	return header
}

func (header *Header) PaddingPercentLeft(padding float64) *Header {
	header.delegated.getFlexNode().StyleSetPaddingPercent(flex.EdgeLeft, float32(padding))
	return header
}

func (header *Header) PaddingPercentHorizontal(padding float64) *Header {
	header.delegated.PaddingPercentLeft(padding).PaddingPercentRight(padding)
	return header
}

func (header *Header) PaddingPercentVertical(padding float64) *Header {
	header.delegated.PaddingPercentTop(padding).PaddingPercentBottom(padding)
	return header
}

func (header *Header) PaddingPercentAll(padding float64) *Header {
	header.delegated.PaddingPercentHorizontal(padding).PaddingPercentVertical(padding)
	return header
}

func (header *Header) PaddingPercent(top float64, right float64, bottom float64, left float64) *Header {
	header.delegated.
		PaddingPercentTop(top).
		PaddingPercentRight(right).
		PaddingPercentBottom(bottom).
		PaddingPercentLeft(left)
	return header
}

// BORDERWIDTH

func (header *Header) BorderWidthTop(borderWidth float64) *Header {
	header.delegated.getFlexNode().StyleSetBorder(flex.EdgeTop, float32(borderWidth))
	return header
}

func (header *Header) BorderWidthRight(borderWidth float64) *Header {
	header.delegated.getFlexNode().StyleSetBorder(flex.EdgeRight, float32(borderWidth))
	return header
}

func (header *Header) BorderWidthBottom(borderWidth float64) *Header {
	header.delegated.getFlexNode().StyleSetBorder(flex.EdgeBottom, float32(borderWidth))
	return header
}

func (header *Header) BorderWidthLeft(borderWidth float64) *Header {
	header.delegated.getFlexNode().StyleSetBorder(flex.EdgeLeft, float32(borderWidth))
	return header
}

func (header *Header) BorderWidthHorizontal(borderWidth float64) *Header {
	header.delegated.BorderWidthLeft(borderWidth).BorderWidthRight(borderWidth)
	return header
}

func (header *Header) BorderWidthVertical(borderWidth float64) *Header {
	header.delegated.BorderWidthTop(borderWidth).BorderWidthBottom(borderWidth)
	return header
}

func (header *Header) BorderWidthAll(borderWidth float64) *Header {
	header.delegated.BorderWidthHorizontal(borderWidth).BorderWidthVertical(borderWidth)
	return header
}

func (header *Header) BorderWidth(top float64, right float64, bottom float64, left float64) *Header {
	header.delegated.
		BorderWidthTop(top).
		BorderWidthRight(right).
		BorderWidthBottom(bottom).
		BorderWidthLeft(left)
	return header
}

// BACKGROUND

func (header *Header) BackgroundColor(red int, green int, blue int, alpha ...float64) *Header {
	header.delegated.backgroundColor = getRgba(red, green, blue, alpha...)
	return header
}

// BORDER COLOR

func (header *Header) BorderColorTop(red int, green int, blue int, alpha ...float64) *Header {
	header.delegated.borderColor[EdgeTop] = getRgba(red, green, blue, alpha...)
	return header
}

func (header *Header) BorderColorRight(red int, green int, blue int, alpha ...float64) *Header {
	header.delegated.borderColor[EdgeRight] = getRgba(red, green, blue, alpha...)
	return header
}

func (header *Header) BorderColorBottom(red int, green int, blue int, alpha ...float64) *Header {
	header.delegated.borderColor[EdgeBottom] = getRgba(red, green, blue, alpha...)
	return header
}

func (header *Header) BorderColorLeft(red int, green int, blue int, alpha ...float64) *Header {
	header.delegated.borderColor[EdgeLeft] = getRgba(red, green, blue, alpha...)
	return header
}

func (header *Header) BorderColorHorizontal(red int, green int, blue int, alpha ...float64) *Header {
	header.delegated.
		BorderColorLeft(red, green, blue, alpha...).
		BorderColorRight(red, green, blue, alpha...)
	return header
}

func (header *Header) BorderColorVertical(red int, green int, blue int, alpha ...float64) *Header {
	header.delegated.
		BorderColorTop(red, green, blue, alpha...).
		BorderColorBottom(red, green, blue, alpha...)
	return header
}

func (header *Header) BorderColorAll(red int, green int, blue int, alpha ...float64) *Header {
	header.delegated.
		BorderColorHorizontal(red, green, blue, alpha...).
		BorderColorVertical(red, green, blue, alpha...)
	return header
}
