// Code generated by PDFlexgo; DO NOT EDIT.
package pdflexgo

import "github.com/kjk/flex"

// CHILDREN

func (page *PageElement) Children(children ...Node) *PageElement {

	for _, child := range children {
		page.getFlexNode().InsertChild(child.getFlexNode(), len(page.getFlexNode().Children))
		page.children = append(page.children, child)
	}

	return page
}

// DIRECTION

func (page *PageElement) Direction(direction Direction) *PageElement {
	page.getFlexNode().StyleSetDirection(flex.Direction(direction))
	return page
}

func (page *PageElement) DirectionInherit() *PageElement {
	return page.Direction(DirectionInherit)
}

func (page *PageElement) DirectionLTR() *PageElement {
	return page.Direction(DirectionLTR)
}

func (page *PageElement) DirectionRTL() *PageElement {
	return page.Direction(DirectionRTL)
}

// FLEX DIRECTION

func (page *PageElement) FlexDirection(direction FlexDirection) *PageElement {
	page.getFlexNode().StyleSetFlexDirection(flex.FlexDirection(direction))
	return page
}

func (page *PageElement) FlexDirectionColumn() *PageElement {
	return page.FlexDirection(FlexDirectionColumn)
}

func (page *PageElement) FlexDirectionColumnReverse() *PageElement {
	return page.FlexDirection(FlexDirectionColumnReverse)
}

func (page *PageElement) FlexDirectionRow() *PageElement {
	return page.FlexDirection(FlexDirectionRow)
}

func (page *PageElement) FlexDirectionRowReverse() *PageElement {
	return page.FlexDirection(FlexDirectionRowReverse)
}

// JustifyContent
func (page *PageElement) JustifyContent(justification Justify) *PageElement {
	page.getFlexNode().StyleSetJustifyContent(flex.Justify(justification))
	return page
}

func (page *PageElement) JustifyContentStart() *PageElement {
	return page.JustifyContent(JustifyStart)
}

func (page *PageElement) JustifyContentCenter() *PageElement {
	return page.JustifyContent(JustifyCenter)
}

func (page *PageElement) JustifyContentEnd() *PageElement {
	return page.JustifyContent(JustifyEnd)
}

func (page *PageElement) JustifyContentSpaceBetween() *PageElement {
	return page.JustifyContent(JustifySpaceBetween)
}

func (page *PageElement) JustifyContentSpaceAround() *PageElement {
	return page.JustifyContent(JustifySpaceAround)
}

// ALIGN CONTENT

func (page *PageElement) AlignContentType(align Align) *PageElement {
	page.getFlexNode().StyleSetAlignContent(flex.Align(align))
	return page
}

func (page *PageElement) AlignContentAuto() *PageElement {
	page.AlignContentType(AlignAuto)
	return page
}

func (page *PageElement) AlignContentStart() *PageElement {
	page.AlignContentType(AlignStart)
	return page
}

func (page *PageElement) AlignContentCenter() *PageElement {
	page.AlignContentType(AlignCenter)
	return page
}

func (page *PageElement) AlignContentEnd() *PageElement {
	page.AlignContentType(AlignEnd)
	return page
}

func (page *PageElement) AlignContentStretch() *PageElement {
	page.AlignContentType(AlignStretch)
	return page
}

func (page *PageElement) AlignContentBaseline() *PageElement {
	page.AlignContentType(AlignBaseline)
	return page
}

func (page *PageElement) AlignContentSpaceBetween() *PageElement {
	page.AlignContentType(AlignSpaceBetween)
	return page
}

func (page *PageElement) AlignContentSpaceAround() *PageElement {
	page.AlignContentType(AlignSpaceAround)
	return page
}

// ALIGN ITEMS

func (page *PageElement) AlignItemsType(align Align) *PageElement {
	page.getFlexNode().StyleSetAlignItems(flex.Align(align))
	return page
}

func (page *PageElement) AlignItemsAuto() *PageElement {
	page.AlignItemsType(AlignAuto)
	return page
}

func (page *PageElement) AlignItemsStart() *PageElement {
	page.AlignItemsType(AlignStart)
	return page
}

func (page *PageElement) AlignItemsCenter() *PageElement {
	page.AlignItemsType(AlignCenter)
	return page
}

func (page *PageElement) AlignItemsEnd() *PageElement {
	page.AlignItemsType(AlignEnd)
	return page
}

func (page *PageElement) AlignItemsStretch() *PageElement {
	page.AlignItemsType(AlignStretch)
	return page
}

func (page *PageElement) AlignItemsBaseline() *PageElement {
	page.AlignItemsType(AlignBaseline)
	return page
}

func (page *PageElement) AlignItemsSpaceBetween() *PageElement {
	page.AlignItemsType(AlignSpaceBetween)
	return page
}

func (page *PageElement) AlignItemsSpaceAround() *PageElement {
	page.AlignItemsType(AlignSpaceAround)
	return page
}

// FLEX WRAP

func (page *PageElement) FlexWrapValue(wrapValue Wrap) *PageElement {
	page.getFlexNode().StyleSetFlexWrap(flex.Wrap(wrapValue))
	return page
}

func (page *PageElement) FlexNoWrap() *PageElement {
	return page.FlexWrapValue(WrapNoWrap)
}

func (page *PageElement) FlexWrap() *PageElement {
	return page.FlexWrapValue(WrapWrap)
}

func (page *PageElement) FlexWrapReverse() *PageElement {
	return page.FlexWrapValue(WrapWrapReverse)
}
